apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
      version: green
  template:
    metadata:
      labels:
        app: nodejs
        version: green
    spec:
      containers:
        - name: nodejs
          image: <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/nodejs-app:green
          env:
            - name: VERSION
              value: "GREEN"
          ports:
            - containerPort: 3000
