apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
      version: blue
  template:
    metadata:
      labels:
        app: nodejs
        version: blue
    spec:
      containers:
        - name: nodejs
          image: <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/nodejs-app:blue
          env:
            - name: VERSION
              value: "BLUE"
          ports:
            - containerPort: 3000
